### ISSUE TITLE
Data.gov site meets requirements from 18F checklist

### ISSUE THREAD

**Issue by hkdctol** [GSA/datagov-deploy#3398]
## User Story

In order to meet basic accessibility requirements, Data.gov PMO needs to review the site using 18F checklist

## Acceptance Criteria

- [ ] GIVEN the new version of Data.gov and new ATO\
  AND the standard checklist provided by 18F\
  THEN Data.gov has a completed review of site following checklist \
  AND specific tickets for any required fixes.

## Background
Among the guides useful for ensuring basic meeting of accessibility requirements, the 18F checklist is useful.

## Sketch
- [ ] Work through 18F checklist https://accessibility.18f.gov/checklist/
- [ ] Make list of issues that do not meet checklist
- [ ] Open individual issues for each item that does not meet checklist
