### ISSUE TITLE
Deploy app to cf

### ISSUE THREAD

**Issue by dano-reisys** [GSA/datagov-deploy#6]
Here is an example on how to deploy wordpress to CF
https://github.com/18F/cf-ex-wordpress

- [x] Research cf existing wordpress buildpack #9
- [x] Research cf manifests #7 
- [x] Figure out how to run composer during cf push #8 
- [x] Figure out how to add SSO support through cf #10
- [x] Add apache config customizations to cf phpbuildpack #9
- [x] Handle wordpress cron jobs #
